"""
ThreatPro - Data Models & Schemas
SQLAlchemy ORM models with corresponding Pydantic validation schemas.
"""

from sqlalchemy import Column, Integer, String, Float, DateTime, Boolean, Text, JSON, Enum as SAEnum
from sqlalchemy.sql import func
from datetime import datetime
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field
import enum

from ..database import Base


# ============================================================================
# ENUMS
# ============================================================================

class RiskCategory(str, enum.Enum):
    SAFE = "Safe"
    SUSPICIOUS = "Suspicious"
    HIGH_RISK = "High Risk"
    ACTIVE_SCAM = "Active Scam"


class AlertSeverity(str, enum.Enum):
    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"
    CRITICAL = "Critical"


class CurrencyDenomination(str, enum.Enum):
    TEN = "₹10"
    TWENTY = "₹20"
    FIFTY = "₹50"
    HUNDRED = "₹100"
    TWO_HUNDRED = "₹200"
    FIVE_HUNDRED = "₹500"
    TWO_THOUSAND = "₹2000"


class TransactionType(str, enum.Enum):
    NEFT = "NEFT"
    RTGS = "RTGS"
    IMPS = "IMPS"
    UPI = "UPI"
    CASH_DEPOSIT = "CASH_DEPOSIT"
    CASH_WITHDRAWAL = "CASH_WITHDRAWAL"


class NodeType(str, enum.Enum):
    ACCOUNT = "Account"
    PHONE = "Phone"
    DEVICE = "Device"
    IP_ADDRESS = "IP_Address"
    LOCATION = "Location"
    VICTIM = "Victim"


# ============================================================================
# SQLALCHEMY ORM MODELS
# ============================================================================

class TranscriptRecord(Base):
    """Stores processed audio transcript chunks with risk scoring."""
    __tablename__ = "transcript_records"

    id = Column(Integer, primary_key=True, index=True)
    call_id = Column(String(64), index=True, nullable=False)
    chunk_index = Column(Integer, default=0)
    transcript_text = Column(Text, nullable=False)
    risk_score = Column(Float, default=0.0)
    risk_category = Column(String(32), default="Safe")
    matched_keywords = Column(JSON, default=list)
    pitch_variance = Column(Float, default=0.0)
    is_spoof = Column(Boolean, default=False)
    timestamp = Column(DateTime, server_default=func.now(), index=True)
    processed = Column(Boolean, default=True)


class ThreatAlert(Base):
    """Real-time threat alerts generated by the interceptor pipeline."""
    __tablename__ = "threat_alerts"

    id = Column(Integer, primary_key=True, index=True)
    alert_id = Column(String(64), unique=True, nullable=False)
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=False)
    severity = Column(String(32), default="Medium")
    source = Column(String(64), default="interceptor")
    risk_score = Column(Float, default=0.0)
    transcript_snippet = Column(Text, default="")
    call_id = Column(String(64), default="")
    related_entities = Column(JSON, default=list)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, server_default=func.now())
    resolved_at = Column(DateTime, nullable=True)


class CurrencyScanResult(Base):
    """Forensic analysis results for currency note verification."""
    __tablename__ = "currency_scan_results"

    id = Column(Integer, primary_key=True, index=True)
    scan_id = Column(String(64), unique=True, nullable=False)
    denomination = Column(String(32), nullable=False)
    is_authentic = Column(Boolean, default=False)
    confidence_score = Column(Float, default=0.0)
    serial_number = Column(String(64), default="")
    serial_valid = Column(Boolean, default=False)
    security_thread_detected = Column(Boolean, default=False)
    security_thread_score = Column(Float, default=0.0)
    uv_fibers_detected = Column(Boolean, default=False)
    uv_fiber_count = Column(Integer, default=0)
    watermark_detected = Column(Boolean, default=False)
    micro_printing_valid = Column(Boolean, default=False)
    anomaly_details = Column(JSON, default=dict)
    visual_overlay_b64 = Column(Text, default="")
    scanned_at = Column(DateTime, server_default=func.now())


class TransactionRecord(Base):
    """Financial transaction records for fraud graph analysis."""
    __tablename__ = "transaction_records"

    id = Column(Integer, primary_key=True, index=True)
    transaction_id = Column(String(64), unique=True, nullable=False, index=True)
    source_account = Column(String(64), index=True, nullable=False)
    target_account = Column(String(64), index=True, nullable=False)
    amount = Column(Float, nullable=False)
    transaction_type = Column(String(32), default="NEFT")
    source_bank = Column(String(128), default="")
    target_bank = Column(String(128), default="")
    source_phone = Column(String(20), default="")
    target_phone = Column(String(20), default="")
    source_ip = Column(String(45), default="")
    device_id = Column(String(64), default="")
    location_lat = Column(Float, nullable=True)
    location_lon = Column(Float, nullable=True)
    location_name = Column(String(255), default="")
    is_suspicious = Column(Boolean, default=False)
    fraud_score = Column(Float, default=0.0)
    cluster_id = Column(Integer, nullable=True)
    timestamp = Column(DateTime, server_default=func.now(), index=True)


class GeoLocation(Base):
    """Geospatial coordinates for cybercrime hotspot mapping."""
    __tablename__ = "geo_locations"

    id = Column(Integer, primary_key=True, index=True)
    location_id = Column(String(64), unique=True, nullable=False)
    latitude = Column(Float, nullable=False)
    longitude = Column(Float, nullable=False)
    location_name = Column(String(255), default="")
    city = Column(String(128), default="")
    state = Column(String(128), default="")
    incident_count = Column(Integer, default=0)
    risk_level = Column(Float, default=0.0)
    cluster_id = Column(Integer, nullable=True)
    last_incident = Column(DateTime, server_default=func.now())
    created_at = Column(DateTime, server_default=func.now())


class PatrolRoute(Base):
    """Optimized patrol routes generated by genetic algorithm."""
    __tablename__ = "patrol_routes"

    id = Column(Integer, primary_key=True, index=True)
    route_id = Column(String(64), unique=True, nullable=False)
    waypoints = Column(JSON, default=list)
    total_distance_km = Column(Float, default=0.0)
    estimated_time_min = Column(Float, default=0.0)
    coverage_score = Column(Float, default=0.0)
    hotspots_covered = Column(Integer, default=0)
    generation = Column(Integer, default=0)
    is_active = Column(Boolean, default=False)
    created_at = Column(DateTime, server_default=func.now())


# ============================================================================
# PYDANTIC SCHEMAS (Request/Response Validation)
# ============================================================================

class TranscriptCreate(BaseModel):
    call_id: str
    chunk_index: int = 0
    transcript_text: str
    audio_data_b64: Optional[str] = None


class TranscriptResponse(BaseModel):
    id: int
    call_id: str
    chunk_index: int
    transcript_text: str
    risk_score: float
    risk_category: str
    matched_keywords: list
    pitch_variance: float
    is_spoof: bool
    timestamp: datetime

    class Config:
        from_attributes = True


class ThreatAlertResponse(BaseModel):
    id: int
    alert_id: str
    title: str
    description: str
    severity: str
    source: str
    risk_score: float
    transcript_snippet: str
    call_id: str
    related_entities: list
    is_active: bool
    created_at: datetime

    class Config:
        from_attributes = True


class CurrencyScanRequest(BaseModel):
    image_b64: str
    denomination_hint: Optional[str] = None


class CurrencyScanResponse(BaseModel):
    scan_id: str
    denomination: str
    is_authentic: bool
    confidence_score: float
    serial_number: str
    serial_valid: bool
    security_thread_detected: bool
    security_thread_score: float
    uv_fibers_detected: bool
    uv_fiber_count: int
    watermark_detected: bool
    micro_printing_valid: bool
    anomaly_details: dict
    visual_overlay_b64: str

    class Config:
        from_attributes = True


class TransactionCreate(BaseModel):
    transaction_id: str
    source_account: str
    target_account: str
    amount: float
    transaction_type: str = "NEFT"
    source_bank: str = ""
    target_bank: str = ""
    source_phone: str = ""
    target_phone: str = ""
    source_ip: str = ""
    device_id: str = ""
    location_lat: Optional[float] = None
    location_lon: Optional[float] = None
    location_name: str = ""


class TransactionResponse(BaseModel):
    id: int
    transaction_id: str
    source_account: str
    target_account: str
    amount: float
    transaction_type: str
    source_bank: str
    target_bank: str
    is_suspicious: bool
    fraud_score: float
    cluster_id: Optional[int]
    timestamp: datetime

    class Config:
        from_attributes = True


class GeoLocationResponse(BaseModel):
    id: int
    location_id: str
    latitude: float
    longitude: float
    location_name: str
    city: str
    state: str
    incident_count: int
    risk_level: float
    cluster_id: Optional[int]

    class Config:
        from_attributes = True


class PatrolRouteResponse(BaseModel):
    id: int
    route_id: str
    waypoints: list
    total_distance_km: float
    estimated_time_min: float
    coverage_score: float
    hotspots_covered: int
    is_active: bool

    class Config:
        from_attributes = True


class GraphNode(BaseModel):
    id: str
    label: str
    node_type: str
    properties: Dict[str, Any] = {}


class GraphEdge(BaseModel):
    source: str
    target: str
    relationship: str
    weight: float = 1.0
    properties: Dict[str, Any] = {}


class GraphData(BaseModel):
    nodes: List[GraphNode]
    edges: List[GraphEdge]


class FraudMuleNetwork(BaseModel):
    network_id: str
    sink_account: str
    total_inflow: float
    transaction_count: int
    source_accounts: List[str]
    risk_score: float
    devices_involved: List[str]
    ips_involved: List[str]


class LegalDossierResponse(BaseModel):
    dossier_id: str
    generated_at: datetime
    case_summary: str
    evidence_count: int
    graph_snapshot: GraphData
    transaction_logs: List[TransactionResponse]
    alerts: List[ThreatAlertResponse]
    sha256_hash: str
    download_url: str